apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: todo-api
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: todo-api
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: todo-frontend
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: todo-frontend
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: postgres
spec:
  maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: postgres
