apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: todo-dev
namePrefix: dev-

resources:
- ../../base

commonLabels:
  env: dev

patches:
- path: replicas-patch.yaml
- path: ingress-patch.yaml
