server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri /index.html;
    }

    # API へのリバプロ (Ingressで分割する場合は不要)
    location /api/ {
        proxy_pass http://todo-api:80/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # ヘルスチェック用
    location = /healthz {
        access_log off;
        return 200 "ok\n";
    }
}
