apiVersion: v1
kind: Secret
metadata:
  name: todo-secret
  labels:
    {{- include "todo.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.postgres.password | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
  JWT_SECRET: {{ .Values.secret.jwtKey | quote }}
